print(dir(str))

s="sunajjusunnysandy"
print(s.capitalize())
l="LLsand"
print(l.casefold())
print(s.center(100))
print(s.count("s"))
print(s.encode())
print(s.endswith("y"))
print(s.expandtabs())
print(s.find("y"))
print(s.format("m"))
print(s.isspace())
print(s.index("j"))
r="123abcd"
#print(r.isalnum()
print(s.isdecimal())
a="9"
print(a.isdigit())
d="a"
print(d.isidentifier())
print(s.isupper())
print(s.islower())
print(a.isnumeric())
print(r.islower())
print(s.removeprefix("s"))
print(s.replace('y','w'))
print(s.removesuffix('y'))
print(s.swapcase())
print(s.title())
print(s.zfill(40))
